name: Smoke

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      PYTHONIOENCODING: utf-8
      PIP_DOWNLOAD_CACHE: ${{ github.workspace }}/../.pip_download_cache
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: [3.7, 3.9]

    steps:
    - name: Set git crlf/eol
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add python requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Add 64-bit mingw-w64 to the PATH
      if: runner.os == 'Windows'
      run: |
        echo "c:/msys64/bin;c:/msys64/mingw64/bin" >> $GITHUB_PATH

    - name: Run tests
      run: |
        tox -e ctest

    #- name: Upload artifacts
      #uses: actions/upload-artifact@v2
      #with:
        #name: coverage-report
        #path: ./cover
