name: Smoke

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      PYTHONIOENCODING: utf-8
      PIP_DOWNLOAD_CACHE: ${{ github.workspace }}/../.pip_download_cache
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]
        python-version: [3.7, 3.9]
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install macos deps
      if: runner.os == 'macOS'
      run: |
        brew install libtool autoconf automake pkg-config autoconf-archive

    - name: Install linux deps
      if: runner.os == 'Linux'
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y autoconf autoconf-archive automake make libtool
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y -s ppa:nerdboy/embedded
        sudo apt-get install -y --only-upgrade autoconf

    - name: Install and setup MSYS2 posix
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: false
        install: |
          gcc
          gcc-libs
          autoconf
          automake
          autoconf-archive
          automake-wrapper
          git
          libtool
          pkg-config
          make
          libiconv-devel

    - name: Add python requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Run tests
      run: |
        tox -e auto
        cat config.h

    #- name: Upload artifacts
      #uses: actions/upload-artifact@v2
      #with:
        #name: coverage-report
        #path: ./cover
