name: Conda Env

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.sh'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'macos-latest', 'windows-2016', 'windows-2019']
        python-version: ['3.9']
        include:
          - os: 'ubuntu-20.04'
            generator: 'Unix Makefiles'
            build_type: 'RelWithDebInfo'
            test_cmd: 'ctest'
          - os: 'macos-latest'
            generator: 'Unix Makefiles'
            build_type: 'RelWithDebInfo'
            test_cmd: 'ctest'
          - os: 'windows-2016'
            generator: 'Visual Studio 15 2017 Win64'
            build_type: 'Release'
            test_cmd: 'trietool.exe'
          - os: 'windows-2019'
            generator: 'Visual Studio 16 2019'
            build_type: 'Release'
            test_cmd: 'trietool.exe'

    steps:
    - name: Set git crlf/eol
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v2

    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: strict

    - name: install prerequisites
      shell: pwsh
      run: conda install cmake ninja c-compiler libiconv

    - name: print info
      shell: pwsh
      run: |
        conda info
        conda list

    - name: build and test
      shell: pwsh
      run: >
        ctest
        --build-config "${{ matrix.build_type }}"
        --build-generator "${{ matrix.generator }}"
        --build-and-test . build
        --build-options -DBUILD_STATIC_LIBS=ON
        -DCMAKE_INSTALL_PREFIX:PATH=$env:CONDA_PREFIX
        --test-command "${{ matrix.test_cmd }}" -V
        --build-config "${{ matrix.build_type }}"
        && cat config.h
