# CI with cmake
name: Cmake

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      PYTHONIOENCODING: utf-8
      PIP_DOWNLOAD_CACHE: ${{ github.workspace }}/../.pip_download_cache
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: [3.7, 3.9]

    steps:
    - name: Set git crlf/eol
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup msys POSIX environment
      uses: msys2/setup-msys2@v2
      if: runner.os == 'Windows'
      with:
        msystem: MSYS
        update: false
        install: git gcc make cmake ninja libiconv-devel

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add python requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Run tests
      if: runner.os != 'Windows'
      run: |
        tox -e ctest

    - name: Run tests
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        set MSYSTEM=MSYS
        tox -e win32
