name: msystem

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

env:
  CTEST_TIME_TIMEOUT: "5"
  CMAKE_GENERATOR: Ninja

jobs:
  msys2-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - msystem: MSYS
            arch: x86_64
            generator: 'MSYS Makefiles'
            build_cfg: Debug
            test_cmd: trietool.exe
          - msystem: MINGW64
            arch: x86_64
            generator: 'MSYS Makefiles'
            build_cfg: Debug
            test_cmd: trietool.exe
          - msystem: MINGW32
            arch: i686
            generator: 'MSYS Makefiles'
            build_cfg: Debug
            test_cmd: trietool.exe
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2

    - name: Setup MinGW native environment
      uses: msys2/setup-msys2@v2
      if: contains(matrix.msystem, 'MINGW')
      with:
        msystem: ${{ matrix.msystem }}
        update: false
        install: >-
          git
          mingw-w64-${{ matrix.arch }}-gcc
          mingw-w64-${{ matrix.arch }}-cmake
          mingw-w64-${{ matrix.arch }}-ninja
          mingw-w64-${{ matrix.arch }}-libiconv

    - name: Setup msys POSIX environment
      uses: msys2/setup-msys2@v2
      if: contains(matrix.msystem, 'MSYS')
      with:
        msystem: MSYS
        update: false
        install: >-
          git
          gcc
          make
          cmake
          ninja
          libiconv-devel

    - name: Build with ctest
      run: >-
        ctest
        --build-config "${{ matrix.build_cfg }}"
        --build-generator "${{ matrix.generator }}"
        --build-and-test . build --parallel
        --build-options -DCMAKE_INSTALL_PREFIX=$PWD/_dist
        --test-command "${{ matrix.test_cmd }}" -V
        --build-config "${{ matrix.build_cfg }}"
        && cat config.h

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: WindowsCMakeTestlog
        path: build/Testing/Temporary/LastTest.log

    - name: Install project
      run: cmake --install build
